version: '3'

services:
  postgresdb:
    image: 'postgres:latest'
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: cars
    volumes:
        - ./pgdata:/var/lib/postgresql/data
    ports:
        - "5432:5432"
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "matheushr97@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - postgresdb
    links:
    - "postgresdb:pgsql-server"  
